version: '3.3'
volumes:
  pg_data7:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    container_name: foodgram_db
    volumes:
      - pg_data7:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: ../.env
    container_name: foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: foodgram_frontend
    command: cp -r /app/build/. /frontend_static/ 
    volumes: 
      - static:/frontend_static 

  nginx:
    build: ../infra/
    container_name: foodgram_nginx
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
      - media:/media
